version: '3.9'

services:
  ml-service:
    image: tensorflow/serving:2.11.0
    container_name: ts-ml-service
    restart: always
    ports:
      - "8501:8501"
    volumes:
      - ./ml/model/sv_format/saved_model:/saved_model
    command: tensorflow_model_server --rest_api_port=8501 --model_name=baseline_model --model_base_path=/saved_model

  web-service:
    build:
      context: ./web
    container_name: fer-web-service
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      URL: ${URL}
    depends_on:
      - ml-service
    volumes:
      - ./web/fer_project:/app
    command: python manage.py runserver 0.0.0.0:8000

